feat: update postlight parser to 2.2.3
kluein/mercury-parser-api pull request #5
Opened 2024-02-14 00:14 UTC by haynesgt

Updates to latest version, as 2.2.0 was years old.

The original project was renamed from postlight/mercury to just postlight/parser

2024-03-04 17:06 UTC, milani requested changes

2024-03-04 17:06 UTC, milani commented on routes.js
> +        req.headers['x-api-key'] !== process.env.TOKEN
now that you are making changes, do you mind using time safe equal? https://nodejs.org/api/crypto.html#cryptotimingsafeequala-b

2024-03-04 17:23 UTC, haynesgt commented on routes.js
> +        req.headers['x-api-key'] !== process.env.TOKEN
ok. I'll also add npm audit fix

2024-03-05 17:46 UTC, milani approved these changes
Can we test it without going to prod first? In other words, do we have a separate deployment for staging? looks like the URL is hard-coded in metaurl 🤔

2024-03-05 17:53 UTC, haynesgt commented
No, we don't deploy in staging I did test it locally. Maybe we can set up a staging deployment.

2024-03-05 17:53 UTC, merged